version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    container_name: ${CONTAINER_NAME}
    network_mode: bridge
    volumes:
      - ./wordpressFiles:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "${WP_EXTERNAL_PORT}:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: host.docker.internal:${DB_PORT}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD','direct');
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${HOST_DOMAIN:-localhost}:${HOST_IP:-host-gateway}"
